build:
  version: "3.0"

loans:
  message: "Welcome to Eazybank loans related APIs"
  contactDetails:
    name: "EazyBank"
    email: "1Y2oK@example.com"
  onCallSupport:
    - "Call us at 1800 1234 1234"
    - "Call us at 1800 1234 1235"






